date: Saturday, March 21st 2026
year: 2026
tbd: true
training:
    date: Friday, March 20th 2026
tickets:
  attendance:
  training:
cft:
  closed: true
cfp:
  closed: true
volunteering:
    day_1: Friday, 03/20
    day_2: Saturday, 03/21
sponsorship:
    package: "/assets/doc/BSidesROC%202026%20Sponsorship%20Kit-1.pdf"
