date: Saturday, March 21st 2026
year: 2026
training:
    date: Friday, March 20th 2026
tickets:
  attendance: https://events.humanitix.com/bsidesroc-2026
  training: https://events.humanitix.com/bsidesroc-2026-training
cft:
  closed: true
cfp:
  closed: true
ctf:
  tbd: false
volunteering:
    day_1: Friday, 03/20
    day_2: Saturday, 03/21
sponsorship:
    package: "/assets/doc/BSidesROC%202026%20Sponsorship%20Kit-1.pdf"
